#!/usr/bin/perl
#use YAML;
#my %total_byets;
#while(<>){
#my($source,$destination,$bytes)=split;
#$total_bytes{$source}{$destination}+=$bytes;
#}
#print Dump(\%total_bytes);
use Storable;
my @data1=qw(one two);
my @data2=qw(two too to);
push @data2,\@data1;
push @data1,\@data2;
store [\@data1,\@data2],"somefile";


my $result=retrieve 'somefile';
use Data::Dumper;
$Data::Dumper::Purity=1;
print Dumper($result);


