#!/usr/bin/perl
open FH, "/etc/passwd" or die "can not open\n";
my @names=<FH>;
my $sum=0;
foreach(@names){

my @n=split ":";
$sum+=$n[2];

print"$n[0] " ,$n[$#n],"\n"if $n[2]==$n[3];
}
print '$sum of uid  is ',$sum,"\n"; 

